import type { EventPayloadProtection } from './event-types'

export const EVENT_PAYLOAD_PROTECTION_CATALOG = {
  ActChanged: 'project-content',
  ActCreated: 'project-content',
  ActDeleted: 'none',
  AIOperationChanged: 'project-content',
  AIOperationRecorded: 'project-content',
  AIProviderSelected: 'project-content',
  AuthoringActivityRecorded: 'project-content',
  AutonomousExceptionActionResolved: 'project-content',
  AutonomousExceptionChanged: 'project-content',
  AutonomousExceptionOpened: 'project-content',
  AutonomousRunChanged: 'project-content',
  AutonomousRunExecutionRequested: 'none',
  AutonomousRunJobAdded: 'project-content',
  AutonomousRunJobChanged: 'project-content',
  AutonomousRunPrepared: 'project-content',
  ChapterChangeSetChanged: 'project-content',
  ChapterChangeSetDrafted: 'project-content',
  ChapterChangeSetItemChanged: 'project-content',
  ChapterCompleted: 'project-content',
  ChapterContentApplied: 'project-content',
  ChapterCreated: 'project-content',
  ChapterDeleted: 'project-content',
  ChapterDetailsChanged: 'project-content',
  ChapterElementAdded: 'project-content',
  ChapterElementChanged: 'project-content',
  ChapterElementRemoved: 'project-content',
  ChapterElementsReplaced: 'project-content',
  ChapterMemoryRecorded: 'project-content',
  ChapterRenamed: 'project-content',
  ChapterVersionRecorded: 'project-content',
  CharacterArcEventCorrected: 'project-content',
  CharacterArcEventRecorded: 'project-content',
  CharacterArcEventRemoved: 'project-content',
  CharacterChanged: 'project-content',
  CharacterCreated: 'project-content',
  CharacterDeleted: 'project-content',
  ConflictChanged: 'project-content',
  ConflictCreated: 'project-content',
  ConflictDeleted: 'project-content',
  ConflictParticipantsReplaced: 'project-content',
  ConflictTimelineRecorded: 'project-content',
  ConflictTimelineRemoved: 'project-content',
  CredentialReferenceChanged: 'project-content',
  ForeshadowingChanged: 'project-content',
  ForeshadowingCharactersReplaced: 'none',
  ForeshadowingCreated: 'project-content',
  ForeshadowingDeleted: 'project-content',
  KnowledgeChunkAdded: 'project-content',
  KnowledgeNoteAdded: 'project-content',
  KnowledgeSourceAdded: 'project-content',
  KnowledgeSourceRemoved: 'project-content',
  OutlineChanged: 'project-content',
  PostprocessRunChanged: 'project-content',
  PostprocessRunRequested: 'project-content',
  PostprocessSuggestionChanged: 'project-content',
  PostprocessSuggestionGenerated: 'project-content',
  ProjectCreated: 'project-content',
  ProjectDeleted: 'none',
  ProjectDeletionRequested: 'none',
  ProjectDetailsChanged: 'project-content',
  ProjectPromptOverrideChanged: 'project-content',
  ProjectSettingsChanged: 'project-content',
  PromptTemplateSelected: 'project-content',
  RelationshipChanged: 'project-content',
  RelationshipCreated: 'project-content',
  RelationshipDeleted: 'project-content',
  SceneChanged: 'project-content',
  SceneContentApplied: 'project-content',
  SceneDeleted: 'project-content',
  ScenePlanned: 'project-content',
  SceneReordered: 'project-content',
  StoryBibleChanged: 'project-content',
  StoryFactChanged: 'project-content',
  StoryFactRecorded: 'project-content',
  StoryFactRemoved: 'project-content',
  StructureTemplateApplied: 'none',
  StyleFingerprintRecorded: 'project-content',
  VolumeChanged: 'project-content',
  VolumeCreated: 'project-content',
  VolumeDeleted: 'none',
  WritingJobChanged: 'project-content',
  WritingJobCreated: 'project-content',
  WritingJobDeleted: 'project-content',
  WritingJobExecutionRequested: 'none',
  WritingJobStepChanged: 'project-content',
  WritingJobStepsReplaced: 'project-content',
} as const satisfies Record<string, EventPayloadProtection>

export function catalogProtectionFor(eventType: string): EventPayloadProtection | undefined {
  if (!Object.hasOwn(EVENT_PAYLOAD_PROTECTION_CATALOG, eventType))
    return undefined
  return (EVENT_PAYLOAD_PROTECTION_CATALOG as Record<string, EventPayloadProtection>)[eventType]
}
